/datum/centcom_announcer/default
	welcome_sounds = list('sound/announcer/classic/welcome.ogg')
	alert_sounds = list('sound/announcer/classic/attention.ogg')
	command_report_sounds = list('sound/announcer/classic/commandreport.ogg')
	event_sounds = list(ANNOUNCER_AIMALF = 'sound/announcer/classic/aimalf.ogg',
		ANNOUNCER_ALIENS = 'sound/announcer/classic/aliens.ogg',
		ANNOUNCER_ANIMES = 'sound/announcer/classic/animes.ogg',
		ANNOUNCER_GRANOMALIES = 'sound/announcer/classic/granomalies.ogg',
		ANNOUNCER_INTERCEPT = 'sound/announcer/classic/intercept.ogg',
		ANNOUNCER_IONSTORM = list('sound/announcer/classic/ionstorm1.ogg', 'sound/announcer/classic/ionstorm2.ogg', 'sound/announcer/classic/ionstorm3.ogg'),
		ANNOUNCER_METEORS = 'sound/announcer/classic/meteors.ogg',
		ANNOUNCER_NEWAI = 'sound/announcer/classic/newai.ogg',
		ANNOUNCER_OUTBREAK5 = 'sound/announcer/classic/outbreak5.ogg',
		ANNOUNCER_OUTBREAK7 = 'sound/announcer/classic/outbreak7.ogg',
		ANNOUNCER_POWEROFF = list('sound/announcer/intern/poweroff_boomer.ogg', 'sound/announcer/classic/poweroff.ogg', 'sound/announcer/classic/poweroff.ogg', 'sound/announcer/classic/poweroff.ogg', 'sound/announcer/classic/poweroff.ogg', 'sound/announcer/classic/poweroff.ogg', 'sound/announcer/classic/poweroff2.ogg'), //Найтл крутой.
		ANNOUNCER_POWERON = list('sound/announcer/classic/poweron1.ogg', 'sound/announcer/classic/poweron2.ogg'), //Ваще.
		ANNOUNCER_RADIATION = 'sound/announcer/classic/radiation.ogg',
		ANNOUNCER_SHUTTLECALLED = 'sound/announcer/classic/shuttlecalled.ogg',
		ANNOUNCER_SHUTTLEDOCK = 'sound/announcer/classic/shuttledock.ogg',
		ANNOUNCER_SHUTTLERECALLED = 'sound/announcer/classic/shuttlerecalled.ogg',
		ANNOUNCER_SPANOMALIES = 'sound/announcer/classic/spanomalies.ogg',
		ANNOUNCER_ADMIN_1 = 'sound/announcer/classic/_admin_cap_gone.ogg',
		ANNOUNCER_ADMIN_2 = 'sound/announcer/classic/_admin_capitain.ogg',
		ANNOUNCER_ADMIN_3 = 'sound/announcer/classic/_admin_horror_music.ogg',
		ANNOUNCER_ADMIN_4 = 'sound/announcer/classic/_admin_hos_gone.ogg',
		ANNOUNCER_ADMIN_5 = 'sound/announcer/classic/_admin_war_pipisky.ogg',
		ANNOUNCER_ADMIN_6 = 'sound/announcer/classic/_admin_war_pizdec.ogg',
		ANNOUNCER_ADMIN_7 = 'sound/announcer/classic/_admin_war_tishina.ogg',
		ANNOUNCER_BSA = 'sound/announcer/classic/artillery.ogg',
		ANNOUNCER_XENO = 'sound/announcer/classic/xeno.ogg',
		ANNOUNCER_IROD = 'sound/announcer/classic/irod.ogg',
		ANNOUNCER_LAMBDA = 'sound/announcer/classic/lambda.ogg')
