/obj/vehicle/sealed/mecha/combat/durand/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/weapon/ballistic/lmg(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/repair_droid(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/antiproj_armor_booster(src)
	ME.attach(src)
	max_ammo()

/obj/vehicle/sealed/mecha/combat/gygax/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/weapon/ballistic/lmg(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/thrusters/ion(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay(src)
	ME.attach(src)
	max_ammo()

/obj/vehicle/sealed/mecha/medical/odysseus/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/medical/mechmedbeam(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/medical/syringe_gun(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/medical/sleeper(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/medical/medigax/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/medical/mechmedbeam(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/thrusters/ion(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/medical/sleeper(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/working/ripley/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/drill(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/thrusters/ion(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/hydraulic_clamp(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/rcd(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/extinguisher(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/working/ripley/mkii/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/drill/diamonddrill(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/hydraulic_clamp(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/weapon/energy/plasma(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/mining_scanner(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/anticcw_armor_booster(src)
	ME.attach(src)

/obj/vehicle/sealed/mecha/working/ripley/firefighter/loaded/Initialize(mapload)
	. = ..()
	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/drill/diamonddrill(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_tracking(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/thrusters/ion(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/hydraulic_clamp(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/rcd(src)
	ME.attach(src)
	ME = new /obj/item/mecha_parts/mecha_equipment/extinguisher(src)
	ME.attach(src)
